[config]

# Waybar color configuration
[templates.waybar]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-stylesheet.css'
output_path = '~/.dotfiles/.config/waybar/colors.css'
post_hook = 'restart-uwsm-app waybar'

# Ghostty color configuration
[templates.ghostty]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-ghostty'
output_path = '~/.dotfiles/.config/wal/templates/colors-ghostty'

# GTK theme color update
[templates.gtk3]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Swaync color configuration
[templates.swaync]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-stylesheet.css'
output_path = '~/.dotfiles/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

# btop
[templates.btop]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-btop.theme'
output_path = '~/.dotfiles/.config/btop/themes/matugen.theme'

# Rofi
[templates.rofi]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-rofi.rasi'
output_path = '~/.dotfiles/.config/rofi/colors.rasi'
