[config]

# Waybar color configuration
[templates.waybar]
input_path = '~/.dotfiles/.config/matugen/configuration/matugen-stylesheet.css'
output_path = '~/.dotfiles/.config/waybar/colors.css'
post_hook = 'restart-uwsm-app waybar'
